name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the project.
title: "[FEATURE] <brief description>"
labels: ["enhancement", "needs triage"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Is your feature request related to a problem?
      description: Please search to see if a similar feature request already exists.
      options:
        - label: I have searched the existing issues and feature requests
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Please describe the feature or enhancement you would like to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case / Motivation
      description: Explain your use case or the motivation behind this feature request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: If you have a suggestion for how to implement this, please describe it here.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: false
