name: 📋 Task
description: Track a specific task or action item to be completed.
title: "[TASK] <brief description>"
labels: ["task", "needs triage"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm and check all that apply before proceeding.
      options:
        - label: I have checked that this task does not already exist in open issues
          required: true
        - label: I have provided enough context for this task
          required: true

  - type: textarea
    attributes:
      label: Task Description
      description: Clearly describe the task to be completed.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this task to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, dependencies, or references for this task.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Related Issues/PRs
      description: Link to any related issues or pull requests (e.g., #123).
    validations:
      required: false
