name: CI - dbt
on: [pull_request]
jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dbt
        run: pip install dbt-fabric
      - name: Run dbt build
        run: |
          dbt deps
          dbt build
